# Generated by Django 5.2.7 on 2025-11-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reservacion_num_invitados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='num_invitados',
            field=models.IntegerField(),
        ),
    ]
