# Generated by Django 5.2.7 on 2025-11-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_reservacion_num_invitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='duracion_horas',
            field=models.IntegerField(default=4),
        ),
    ]
