# Generated by Django 5.2.7 on 2025-11-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reservacion_duracion_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLEADO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('id_empleado', models.CharField(max_length=10)),
            ],
        ),
    ]
