# Generated by Django 5.2.7 on 2025-11-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='id_empleado',
            field=models.CharField(default='777', max_length=10),
        ),
    ]
