# Generated by Django 5.2.7 on 2025-11-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_empleado_id_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='nombre_empleado',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='id_empleado',
        ),
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contraseña',
            field=models.CharField(default='777', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
