# Generated by Django 5.2.7 on 2025-11-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_nombre_empleado_empleado_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_usuario',
            field=models.CharField(default='empleado', max_length=50),
        ),
    ]
