# Generated by Django 5.2.7 on 2025-11-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_empleado_nombre_empleado_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_usuario',
            field=models.CharField(default='Empleado', max_length=50),
        ),
    ]
