# Generated by Django 5.2.7 on 2025-11-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_empleado_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
