# Generated by Django 5.2.7 on 2025-11-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_contraseña_empleado_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipo_usuario',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='contrasena',
            field=models.CharField(default='777', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
