# Generated by Django 5.2.7 on 2025-11-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_admin_remove_empleado_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='EMPLEADO',
        ),
    ]
