# Generated by Django 5.2.7 on 2025-11-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_admin_delete_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='caracteristicas',
            field=models.TextField(default='Ninguna'),
        ),
    ]
