# Generated by Django 5.2.8 on 2025-11-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_show_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='estatus',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='show',
            name='caracteristicas',
            field=models.TextField(default='NINGUNA'),
        ),
    ]
